"""Diagnostic adapter for the official Falcao Labour Court repository."""

from __future__ import annotations

import hashlib
from typing import Any
from urllib.parse import urlparse
from uuid import uuid4

import requests

from nanojuris.config import NanoJurisConfig, configure_requests_session
from nanojuris.errors import (
    AccessControlRequiredError,
    ParserContractChangedError,
    QueryRejectedError,
    RateLimitDetectedError,
    SourceUnavailableError,
)
from nanojuris.models import (
    AccessStatus,
    DecisionBundle,
    ExtractionStatus,
    JurisprudenceQuery,
    JurisprudenceResult,
    ProviderCapabilities,
    ProviderCatalog,
    ProviderOption,
    SearchPage,
    SourceTrace,
)
from nanojuris.providers.base import JurisprudenceProvider
from nanojuris.transport import SharedHttpClient
from nanojuris.transport.models import TransportPolicy, TransportRequest, TransportStatus

_BLOCK_MARKERS = ("cloudfront", "request blocked", "generated by cloudfront")
_SHELL_MARKERS = ("falcão", "falcao", "jurisprudência", "jurisprudencia", "ng-version")


_API_PATH = "/no-auth/pesquisa"


class FalcaoJtProvider(JurisprudenceProvider):
    """Probe Falcao availability without claiming an unobserved API contract."""

    name = "falcao_jt"

    def __init__(
        self,
        config: NanoJurisConfig | None = None,
        session: requests.Session | None = None,
    ) -> None:
        self.config = config or NanoJurisConfig()
        self.session = configure_requests_session(session or requests.Session(), self.config)
        host = urlparse(self.config.falcao_jt_url).hostname or ""
        self.transport = SharedHttpClient(
            TransportPolicy(
                allowed_hosts=(host,),
                timeout_seconds=self.config.timeout,
                max_bytes=2_000_000,
                max_retries=0,
                rate_limit_interval=self.config.rate_limit_interval,
                user_agent=self.config.user_agent,
                verify_ssl=self.config.verify_ssl,
            ),
            session=self.session,
        )
        self._results: dict[str, JurisprudenceResult] = {}

    def search(self, query: JurisprudenceQuery) -> SearchPage:
        _validate_query(query)
        response = self._request(
            f"{self.config.falcao_jt_api_url.rstrip('/')}{_API_PATH}",
            params=_search_params(query),
            operation="search",
        )
        return _parse_search_response(response, query, self._results)

    def search_authorized(
        self,
        query: JurisprudenceQuery,
        *,
        access_token: str,
    ) -> SearchPage:
        """Run one bounded search using a caller-supplied OIDC access token.

        Falcao's frontend currently advertises an OIDC redirect while the
        public ``/no-auth`` route returns HTTP 403.  This method is the safe
        handoff for an operator who has already completed the official login:
        the short-lived bearer value is accepted for this request only and is
        never persisted, put in a trace, or reused by the provider.
        """

        _validate_query(query)
        token = access_token.strip()
        if not token:
            raise AccessControlRequiredError(
                "Falcao/JT exige token OIDC fornecido pela sessao oficial"
            )
        response = self._request(
            f"{self.config.falcao_jt_api_url.rstrip('/')}{_API_PATH}",
            params=_search_params(query),
            headers={"Authorization": f"Bearer {token}"},
            operation="authorized_search",
        )
        return _parse_search_response(response, query, self._results)

    def get_decisions(self, precedent_id: str) -> DecisionBundle:
        result = self._results.get(precedent_id)
        if result is None:
            raise SourceUnavailableError(
                "Falcao/JT detalhe disponivel somente apos busca observada"
            )
        return DecisionBundle(
            precedent_id=precedent_id,
            source=self.name,
            texts=[
                {
                    "content": result.full_text or result.summary or "",
                    "content_type": "text/html",
                }
            ],
            source_trace=result.source_trace,
            raw={"access_status": result.access_status.value if result.access_status else None},
        )

    def get_parameters(self) -> dict[str, Any]:
        return {
            "source_url": self.config.falcao_jt_url,
            "api_url": self.config.falcao_jt_api_url,
            "public_search_endpoint": f"{self.config.falcao_jt_api_url.rstrip('/')}{_API_PATH}",
            "scope": "national_labor_first_and_second_degree",
            "status": "blocked_or_inconclusive",
            "authorized_status": "caller_supplied_oidc_token_only",
            "result_contract": "documentos_quantidadeTotal",
            "metadata_endpoints": [
                "/no-auth/informacao/versao",
                "/no-auth/informacao/dataIndexacaoDados",
                "/no-auth/informacao/dataPublicacaoDados",
                "/no-auth/informacao/tribunais/codigosTrt",
            ],
        }

    def get_catalog(self) -> ProviderCatalog:
        """Load the public TRT code catalog without running a search."""

        response = self._request(
            f"{self.config.falcao_jt_api_url.rstrip('/')}/no-auth/informacao/tribunais/codigosTrt",
            operation="public_metadata",
        )
        try:
            payload = response.json()
        except (TypeError, ValueError) as exc:
            raise ParserContractChangedError("Falcao/JT catalogo nao retornou JSON valido") from exc
        if not isinstance(payload, dict) or not isinstance(payload.get("codigos"), str):
            raise ParserContractChangedError("Falcao/JT catalogo nao retornou codigosTrt")
        codes = [
            value for value in payload["codigos"].replace(" e ", ", ").split(",") if value.strip()
        ]
        courts = [
            ProviderOption(
                code=f"TRT{value.strip()}",
                description=f"Tribunal Regional do Trabalho {value.strip()}",
            )
            for value in codes
            if value.strip().isdigit()
        ]
        return ProviderCatalog(
            source=self.name,
            courts=courts,
            source_trace=_trace(response, JurisprudenceQuery(text="__metadata__")),
            raw={"status": "public_metadata", "codes": codes},
        )

    def get_capabilities(self) -> ProviderCapabilities:
        filters = [
            "text",
            "number",
            "case_class",
            "degree",
            "instance",
            "document_type",
            "judgment_date_from",
            "judgment_date_to",
        ]
        return ProviderCapabilities(
            source=self.name,
            display_name="Falcao JT (diagnostico opt-in)",
            source_url=self.config.falcao_jt_url,
            category="court_jurisprudence",
            search_modes=[
                "text",
                "case_number",
                "filters",
                "catalog",
                "authorized_oidc_session",
            ],
            document_types=["sentenca", "acordao", "decisao_monocratica", "precedent"],
            content_formats=["html", "json"],
            canonical_records=["CanonicalDecision"],
            semantic_discriminator=(
                "repository_scope=official_labor_national;degree=unknown_until_result"
            ),
            extracted_fields=[
                "authority",
                "degree",
                "case_number",
                "case_class",
                "decision_type",
                "rapporteur",
                "judging_body",
                "judgment_date",
                "publication_date",
                "summary",
                "full_text",
                "document_url",
            ],
            access_statuses=[
                AccessStatus.PUBLIC,
                AccessStatus.ACCESS_CONTROL_REQUIRED,
                AccessStatus.SOURCE_UNAVAILABLE,
            ],
            endpoints=[
                f"GET {urlparse(self.config.falcao_jt_url).path or '/'}",
                f"GET {_API_PATH}",
                "GET /no-auth/informacao/versao",
                "GET /no-auth/informacao/dataIndexacaoDados",
                "GET /no-auth/informacao/dataPublicacaoDados",
                "GET /no-auth/informacao/tribunais/codigosTrt",
            ],
            supports_catalog=True,
            supports_unified_search=False,
            opt_in_unified_search=True,
            supports_mcp=True,
            supports_cli=True,
            supports_live_tests=True,
            pagination_mode="unknown_until_contract",
            completeness_contract="unknown_until_contract",
            full_text_access="unknown",
            supported_filters=[],
            unsupported_filters=filters,
            filter_semantics={name: "unsupported" for name in filters},
            limitations=[
                "A rota publica respondeu CloudFront ou shell sem contrato de resultados.",
                "A busca autorizada exige token OIDC fornecido pela sessao oficial; "
                "o provider nao executa login nem persiste o token.",
                "O Falcao permanece candidato e fora da federacao padrao.",
                "Nenhum cookie, token, sessao, proxy ou bypass e utilizado.",
            ],
            responsible_use=[
                "Solicitar API, exportacao ou allowlist ao responsavel da fonte; "
                "nao contornar bloqueios."
            ],
        )

    def _request(
        self,
        url: str,
        *,
        params: dict[str, str] | None = None,
        headers: dict[str, str] | None = None,
        operation: str = "availability_probe",
    ) -> Any:
        request = TransportRequest(
            source=self.name,
            operation=operation,
            method="GET",
            url=url,
            params=params or {},
            headers={
                "Accept": "application/json, text/plain, */*",
                **(headers or {}),
            },
            idempotent=True,
            # Authorized responses must never be shared through the optional
            # live-response cache, even if a caller injects a cached client.
            cacheable=False,
        )
        try:
            response = self.transport.request(request)
        except requests.exceptions.Timeout as exc:
            raise SourceUnavailableError("Falcao/JT request timeout") from exc
        except requests.exceptions.SSLError as exc:
            raise SourceUnavailableError("Falcao/JT TLS negotiation failed") from exc
        except requests.RequestException as exc:
            raise SourceUnavailableError("Falcao/JT request failed") from exc
        except SourceUnavailableError as exc:
            raise SourceUnavailableError(f"Falcao/JT transport failed: {exc}") from exc
        if response.status is not TransportStatus.COMPLETE:
            raise SourceUnavailableError(
                f"Falcao/JT transport failed: {response.error_type or response.status.value}"
            )
        status_code = response.status_code
        if status_code is None:
            raise SourceUnavailableError("Falcao/JT transport returned no HTTP status")
        if status_code == 429:
            raise RateLimitDetectedError("Falcao/JT returned HTTP 429")
        if status_code in {401, 403, 407, 451}:
            raise AccessControlRequiredError(f"Falcao/JT returned HTTP {status_code}")
        if status_code < 200 or status_code >= 300:
            raise SourceUnavailableError(f"Falcao/JT returned HTTP {status_code}")
        return response


def _validate_query(query: JurisprudenceQuery) -> None:
    if not any((query.text.strip(), query.number.strip(), query.exact_phrase.strip())):
        raise QueryRejectedError("Falcao/JT exige termo, numero ou frase exata")


def _search_params(query: JurisprudenceQuery) -> dict[str, str]:
    collections = [item.strip() for item in query.collection.split(",") if item.strip()]
    if not collections:
        collections = ["acordaos"]
    params = {
        "sessionId": str(uuid4()),
        "latitude": "",
        "longitude": "",
        "pais": "",
        "texto": (query.exact_phrase or query.text or query.all_words).strip(),
        "page": str(max(query.page, 1)),
        "size": str(min(max(query.page_size, 1), 100)),
        "colecao": ",".join(collections),
        "temEmenta": "true",
        "pesquisaSomenteNasEmentas": "false",
        "ordenacao": query.order_by or "relevancia",
    }
    if query.number.strip():
        params["texto"] = query.number.strip()
    if query.courts:
        params["tribunais"] = ",".join(query.courts)
    if query.rapporteur:
        params["nomeRelator"] = query.rapporteur
    if query.judging_body:
        params["orgaoJulgador"] = query.judging_body
    if query.case_class:
        params["classeProcesso"] = query.case_class
    start = query.judgment_date_from or query.published_from
    end = query.judgment_date_to or query.published_to
    if start:
        params["dataInicio"] = start
    if end:
        params["dataFim"] = end
    return params


def _parse_search_response(
    response: Any,
    query: JurisprudenceQuery,
    result_store: dict[str, JurisprudenceResult],
) -> SearchPage:
    """Parse one Falcao result window shared by public and authorized paths."""

    text = response.text.casefold()
    if any(marker in text for marker in _BLOCK_MARKERS):
        raise AccessControlRequiredError(
            "Falcao/JT retornou bloqueio de distribuicao; nenhum resultado foi obtido"
        )
    if "html" in (response.content_type or "").casefold() and any(
        marker in text for marker in _SHELL_MARKERS
    ):
        raise ParserContractChangedError(
            "Falcao/JT retornou apenas o shell publico; contrato de resultados ausente"
        )
    try:
        payload = response.json()
    except (TypeError, ValueError) as exc:
        raise ParserContractChangedError("Falcao/JT pesquisa nao retornou JSON valido") from exc
    if not isinstance(payload, dict):
        raise ParserContractChangedError("Falcao/JT pesquisa retornou envelope inesperado")
    documents = payload.get("documentos")
    if documents is None:
        raise ParserContractChangedError("Falcao/JT pesquisa nao retornou o campo documentos")
    if not isinstance(documents, list):
        raise ParserContractChangedError("Falcao/JT documentos nao sao uma lista")
    trace = _trace(response, query)
    results = [_parse_document(item, trace) for item in documents if isinstance(item, dict)]
    if any(result is None for result in results):
        raise ParserContractChangedError(
            "Falcao/JT documento nao possui identificador ou tipo reconhecivel"
        )
    typed = [result for result in results if result is not None]
    result_store.update({result.id: result for result in typed})
    reported_total = payload.get("quantidadeTotal")
    total_known = isinstance(reported_total, int) and reported_total >= 0
    total_value = reported_total if isinstance(reported_total, int) else len(typed)
    explicit_empty = total_known and total_value == 0
    if explicit_empty and typed:
        raise ParserContractChangedError("Falcao/JT retornou documentos junto de quantidadeTotal=0")
    unconfirmed_empty = not typed and not explicit_empty
    page_complete = explicit_empty or (total_known and len(typed) >= total_value)
    return SearchPage(
        source="falcao_jt",
        total=total_value,
        total_known=total_known,
        start=(query.page - 1) * query.page_size + 1 if typed else 0,
        end=(query.page - 1) * query.page_size + len(typed) if typed else 0,
        page=query.page,
        page_size=query.page_size,
        results=typed,
        source_trace=trace,
        pagination_mode="offset",
        is_complete=page_complete,
        completeness_reason=(
            None
            if total_known
            else "Falcao nao informou total autoritativo; janela vazia nao confirmada"
        ),
        ordering="source_default",
        access_status=AccessStatus.PUBLIC,
        extraction_status=(
            ExtractionStatus.EMPTY
            if explicit_empty
            else ExtractionStatus.PARTIAL
            if unconfirmed_empty
            else ExtractionStatus.COMPLETE
        ),
    )


def _parse_document(item: dict[str, Any], trace: SourceTrace) -> JurisprudenceResult | None:
    collection_raw = str(
        item.get("colecao") or item.get("origemDocumentos") or item.get("tipoDocumento") or ""
    ).strip()
    collection_key = collection_raw.casefold()
    collection_map = {
        "acordaos": "acordaos",
        "acordao": "acordaos",
        "sentencas": "sentencas",
        "sentenca": "sentencas",
        "decisoesmonocraticas": "decisoesmonocraticas",
        "decisao_monocratica": "decisoesmonocraticas",
        "recursorevista": "recursorevista",
    }
    collection = collection_map.get(collection_key, collection_raw or None)
    document_type = {
        "acordaos": "acordao",
        "sentencas": "sentenca",
        "decisoesmonocraticas": "decisao_monocratica",
        "recursorevista": "decisao_admissibilidade",
    }.get(collection or "", str(item.get("tipoDocumento") or "").strip() or None)
    identifier = str(
        item.get("idDocumentoAcordao")
        or item.get("idDocumentoSentenca")
        or item.get("idDocumento")
        or item.get("id")
        or ""
    ).strip()
    if not identifier or not document_type:
        return None
    full_text = (
        str(
            item.get("textoAcordao")
            or item.get("textoSentenca")
            or item.get("textoRecursoRevista")
            or item.get("conteudoDocumento")
            or item.get("texto")
            or ""
        ).strip()
        or None
    )
    summary = str(item.get("textoEmenta") or item.get("ementa") or "").strip() or None
    degree = _normalize_degree(
        item.get("degree") or item.get("grau") or item.get("instancia") or item.get("instance")
    )
    authority = str(item.get("tribunal") or item.get("siglaTribunal") or "").strip() or None
    number = str(item.get("numeroProcesso") or item.get("processo") or "").strip() or None
    return JurisprudenceResult(
        id=identifier,
        source="falcao_jt",
        court=authority or "JT",
        type=document_type,
        number=number,
        summary=summary,
        full_text=full_text,
        rapporteur=str(item.get("nomeRelator") or item.get("relator") or "").strip() or None,
        judgment_date=str(item.get("dataJulgamento") or item.get("data") or "").strip() or None,
        publication_date=str(item.get("dataPublicacao") or "").strip() or None,
        access_status=AccessStatus.PUBLIC,
        extraction_status=ExtractionStatus.COMPLETE
        if full_text or summary
        else ExtractionStatus.PARTIAL,
        degree=degree,
        authority=authority,
        collection=collection,
        document_type=document_type,
        document_url=str(item.get("documentUrl") or item.get("url") or "").strip() or None,
        source_trace=trace,
        raw=item,
    )


def _normalize_degree(value: object) -> str | None:
    normalized = str(value or "").strip().casefold()
    if normalized in {"2", "2o", "segundo", "segundo grau", "second"}:
        return "second"
    if normalized in {"1", "1o", "primeiro", "primeiro grau", "first"}:
        return "first"
    return None


def _trace(response: Any, query: JurisprudenceQuery) -> SourceTrace:
    return SourceTrace(
        provider="falcao_jt",
        endpoint="GET /no-auth/pesquisa",
        source_url="https://jurisprudencia.jt.jus.br/jurisprudencia-nacional-backend/api/no-auth/pesquisa",
        final_url=getattr(response, "final_url", None),
        http_status=getattr(response, "status_code", None),
        content_type=getattr(response, "content_type", None),
        content_sha256=getattr(response, "content_sha256", None)
        or hashlib.sha256(getattr(response, "body", b"")).hexdigest(),
        response_bytes=len(getattr(response, "body", b"")),
        query={"page": query.page, "page_size": query.page_size},
        retrieval_status="ok",
        transformations=["falcao_public_api_v1"],
    )
