import type { WorkbenchPayload, WorkbenchResult, WorkbenchSource } from "./types";

const source = (
  id: string,
  displayName: string,
  category: string,
  count: number,
  status: WorkbenchSource["status"],
  fullText: WorkbenchSource["fullText"],
): WorkbenchSource => ({
  source: id,
  displayName,
  category,
  count,
  status,
  fullText,
  latency: status === "blocked" ? "--" : `${(1.4 + count / 100).toFixed(1)} s`,
  tier: status === "healthy" ? "gold" : status === "partial" ? "silver" : "restricted",
});

const result = (item: Partial<WorkbenchResult> & Pick<WorkbenchResult, "id" | "source" | "court" | "title" | "summary">): WorkbenchResult => ({
  type: "Acórdão",
  fullText: "",
  caseNumber: "Não informado",
  rapporteur: "Não informado",
  judgingBody: "Não informado",
  judgmentDate: "Não informado",
  publicationDate: "Não informado",
  documentStatus: "summary_only",
  contentType: "text/html",
  byteSize: "--",
  sha256: "não calculado",
  parser: "canonical-mock-v1",
  endpoint: "/api/search",
  accessStatus: "public",
  retrievalStatus: "ok",
  extractionStatus: "complete",
  raw: {},
  ...item,
});

export const mockSources: WorkbenchSource[] = [
  source("stf_juris", "STF", "superiores", 12, "healthy", "available"),
  source("stj_scon", "STJ", "superiores", 24, "healthy", "available"),
  source("tjdf_juris", "TJDFT", "estaduais", 8, "healthy", "loaded"),
  source("tjto_jurisprudencia", "TJTO", "estaduais", 6, "healthy", "loaded"),
  source("tjba_graphql", "TJBA", "estaduais", 11, "healthy", "loaded"),
  source("trf4_eproc_jurisprudencia", "TRF4", "federais", 5, "healthy", "available"),
  source("tst_jurisprudencia", "TST", "superiores", 9, "healthy", "loaded"),
  source("tcu_jurisprudencia", "TCU", "contexto", 4, "partial", "summary_only"),
  source("tjsp_cjsg", "TJSP CJSG", "estaduais", 0, "blocked", "blocked"),
];

export const mockResults: WorkbenchResult[] = [
  result({
    id: "tjdf-0712345",
    source: "tjdf_juris",
    court: "TJDFT",
    title: "Responsabilidade civil por falha na prestação de serviço",
    summary: "A responsabilidade civil do fornecedor pode ser reconhecida quando demonstrada a falha na prestação do serviço e o nexo com o dano experimentado pelo consumidor.",
    caseNumber: "0712345-12.2024.8.07.0001",
    rapporteur: "Des. Carlos Almeida",
    judgingBody: "5ª Turma Cível",
    judgmentDate: "18 abr. 2024",
    publicationDate: "25 abr. 2024",
    documentStatus: "loaded",
    contentType: "text/html",
    byteSize: "18.029 bytes",
    sha256: "a7e4...91f2",
    fullText: "A responsabilidade civil do fornecedor pode ser reconhecida quando demonstrada a falha na prestação do serviço e o nexo causal com o dano experimentado pelo consumidor.\n\nNo caso examinado, os documentos demonstram que a prestação contratada não observou o padrão de segurança legitimamente esperado.",
    endpoint: "/buscaLivre2",
  }),
  result({
    id: "tjto-0823441",
    source: "tjto_jurisprudencia",
    court: "TJTO",
    title: "Dano moral e falha na prestação de serviço de transporte",
    summary: "A tese estruturada distingue o mero inadimplemento contratual da lesão relevante aos direitos da personalidade.",
    caseNumber: "0008234-41.2023.8.27.2700",
    rapporteur: "Des. Ana Ribeiro",
    judgingBody: "2ª Câmara Cível",
    judgmentDate: "03 maio 2024",
    publicationDate: "10 maio 2024",
    documentStatus: "loaded",
    contentType: "application/pdf",
    byteSize: "24.610 bytes",
    sha256: "9c21...d812",
    fullText: "A análise do conjunto probatório demonstra que o atraso ultrapassou o limite do mero dissabor. A decisão considera a duração do evento, a assistência oferecida e os efeitos concretos na esfera pessoal da parte.",
    parser: "tjto-pdf-v1",
    endpoint: "viewFileDoc.php",
  }),
  result({
    id: "tjba-0042199",
    source: "tjba_graphql",
    court: "TJBA",
    title: "Dever de indenizar e responsabilidade objetiva",
    summary: "A decisão examina a incidência da responsabilidade objetiva e os limites da prova do dano em relação de consumo.",
    caseNumber: "0042199-72.2022.8.05.0001",
    rapporteur: "Des. Maria Santos",
    judgingBody: "3ª Câmara Cível",
    judgmentDate: "11 mar. 2023",
    publicationDate: "20 mar. 2023",
    documentStatus: "available",
    contentType: "application/json",
    byteSize: "disponível sob demanda",
    sha256: "não carregado",
    fullText: "A responsabilidade objetiva não dispensa a demonstração do dano e do nexo causal. A incidência do regime consumerista deve ser examinada em conjunto com a prova produzida nos autos.",
    endpoint: "/graphql",
  }),
  result({
    id: "tst-1002834",
    source: "tst_jurisprudencia",
    court: "TST",
    title: "Responsabilidade do empregador por acidente de trabalho",
    summary: "A decisão reúne critérios para a análise do dever de reparação em acidente relacionado ao ambiente laboral.",
    caseNumber: "1002834-61.2021.5.00.0000",
    rapporteur: "Min. Helena Costa",
    judgingBody: "6ª Turma",
    judgmentDate: "21 fev. 2024",
    publicationDate: "01 mar. 2024",
    documentStatus: "loaded",
    contentType: "text/html",
    byteSize: "31.420 bytes",
    sha256: "40a1...cce0",
    fullText: "A responsabilidade do empregador exige a leitura integrada das normas de segurança, das circunstâncias do acidente e da conduta adotada após o evento.",
    endpoint: "/rest/documentos/{id}",
  }),
  result({
    id: "stj-154872",
    source: "stj_scon",
    court: "STJ",
    title: "Responsabilidade civil e quantificação do dano",
    summary: "O julgado apresenta fundamentos utilizados na quantificação da indenização por dano extrapatrimonial.",
    caseNumber: "REsp 1.548.721/SP",
    rapporteur: "Min. Roberto Lima",
    judgingBody: "Quarta Turma",
    judgmentDate: "07 nov. 2022",
    publicationDate: "16 nov. 2022",
    documentStatus: "available",
    contentType: "application/pdf",
    byteSize: "disponível sob demanda",
    sha256: "não carregado",
    fullText: "A quantificação do dano extrapatrimonial deve considerar a extensão da lesão, a capacidade econômica das partes, a finalidade compensatória e a vedação ao enriquecimento sem causa.",
    parser: "stj-scon-pdf-v1",
    endpoint: "/scon/documento",
  }),
  result({
    id: "trf4-803420",
    source: "trf4_eproc_jurisprudencia",
    court: "TRF4",
    title: "Responsabilidade civil do Estado",
    summary: "Resultado demonstrativo de tribunal federal, com ementa disponível e inteiro teor dependente de carregamento.",
    caseNumber: "5008034-20.2021.4.04.0000",
    rapporteur: "Des. Federal João Vidal",
    judgingBody: "4ª Turma",
    judgmentDate: "29 jan. 2024",
    publicationDate: "06 fev. 2024",
    documentStatus: "available",
    contentType: "application/pdf",
    byteSize: "disponível sob demanda",
    sha256: "não carregado",
    fullText: "O dever de indenizar do Estado deve ser examinado a partir da conduta administrativa, do dano comprovado e da relação de causalidade reconhecida no caso concreto.",
    endpoint: "/jurisprudencia/documento",
  }),
];

export function createMockPayload(query: string, state: string): WorkbenchPayload {
  const isEmpty = state === "empty";
  const isBlocked = state === "blocked";
  const visible = isEmpty ? [] : isBlocked ? mockResults.filter((item) => item.source === "tjsp_cjsg") : mockResults;
  return {
    sources: mockSources,
    results: visible,
    total: isEmpty || isBlocked ? 0 : visible.length,
    totalAvailable: isEmpty || isBlocked ? 0 : visible.length,
    totalReturned: isEmpty || isBlocked ? 0 : visible.length,
    deduplicatedTotal: isEmpty || isBlocked ? 0 : visible.length,
    page: 1,
    pageSize: visible.length,
    hasMore: false,
    nextPage: null,
    elapsed: "2,8 s",
    completeness: state === "partial" ? "7 fontes retornaram conteúdo parcial" : state === "blocked" ? "Acesso limitado não significa ausência de jurisprudência" : "completude observada 92%",
    sourceStatus: Object.fromEntries(mockSources.map((item) => [item.source, { status: item.status === "healthy" ? "ok" : item.status, count: item.count }])),
    skippedSources: state === "blocked" ? ["tjsp_cjsg"] : [],
    errors: [],
    sourcesComplete: mockSources.filter((item) => item.status === "healthy").map((item) => item.source),
    sourcesPartial: mockSources.filter((item) => item.status === "partial").map((item) => item.source),
    sourcesUnknown: [],
    collectionComplete: state !== "partial" && state !== "blocked",
    query,
    mode: "mock",
  };
}
